repo_url: https://github.com/hect0x7/JMComic-Crawler-Python
repo_name: hect0x7/JMComic-Crawler-Python
site_name: jmcomic

theme:
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: 切换到浅色主题
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: 切换到深色主题
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: 主题跟随系统
  name: material
  features:
    - navigation.sections
    - content.code.copy
    - content.code.select
    - search.suggest
    - search.highlight
    - search.share
    - navigation.tabs
    - navigation.top
plugins:
  - search
  - mkdocstrings:
      handlers:
        # See: https://mkdocstrings.github.io/python/usage/
        python:
          paths: [ '../../src/' ]
          options:
            preload_modules:
              - common
            docstring_style: sphinx
            filters:
              - 'AbstractJmClient'
              - 'AutoSetBrowserCookiesPlugin'
              - 'CacheRegistry'
              - 'ClientProxyPlugin'
              - 'ConvertJpgToPdfPlugin'
              - 'DeleteDuplicatedFilesPlugin'
              - 'DetailEntity'
              - 'DirRule'
              - 'DoNotDownloadImage'
              - 'DownloadCallback'
              - 'Downloadable'
              - 'ExceptionTool'
              - 'FavoriteFolderExportPlugin'
              - 'FindUpdatePlugin'
              - 'ImageSuffixFilterPlugin'
              - 'Img2pdfPlugin'
              - 'IndexedEntity'
              - 'JmAlbumCommentResp'
              - 'JmAlbumDetail'
              - 'JmApiAdaptTool'
              - 'JmApiClient'
              - 'JmApiResp'
              - 'JmBaseEntity'
              - 'JmCategoryClient'
              - 'JmCategoryPage'
              - 'JmCryptoTool'
              - 'JmDetailClient'
              - 'JmDownloader'
              - 'JmFavoritePage'
              - 'JmHtmlClient'
              - 'JmImageClient'
              - 'JmImageDetail'
              - 'JmImageResp'
              - 'JmImageTool'
              - 'JmJsonResp'
              - 'JmLoginPlugin'
              - 'JmMagicConstants'
              - 'JmModuleConfig'
              - 'JmOption'
              - 'JmOptionPlugin'
              - 'JmPageContent'
              - 'JmPageTool'
              - 'JmPhotoDetail'
              - 'JmResp'
              - 'JmSearchAlbumClient'
              - 'JmSearchPage'
              - 'JmServerPlugin'
              - 'JmUserClient'
              - 'JmcomicClient'
              - 'JmcomicException'
              - 'JmcomicText'
              - 'JsonResolveFailException'
              - 'JustDownloadSpecificCountImage'
              - 'LogTopicFilterPlugin'
              - 'LongImgPlugin'
              - 'MissingAlbumPhotoException'
              - 'PatternTool'
              - 'PhotoConcurrentFetcherProxy'
              - 'PluginValidationException'
              - 'RegularNotMatchException'
              - 'ReplacePathStringPlugin'
              - 'RequestRetryAllFailException'
              - 'ResponseUnexpectedException'
              - 'SendQQEmailPlugin'
              - 'SkipPhotoWithFewImagesPlugin'
              - 'SubscribeAlbumUpdatePlugin'
              - 'UsageLogPlugin'
              - 'ZipPlugin'
              - 'create_option'
              - 'create_option_by_env'
              - 'create_option_by_file'
              - 'create_option_by_str'
              - 'default_jm_logging'
              - 'disable_jm_log'
              - 'download_album'
              - 'download_batch'
              - 'download_photo'
              - 'new_downloader'
              - 'register_jmcomic_component'
markdown_extensions:
  - attr_list
  - toc:
      permalink: true
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

docs_dir: sources